---
- name: write config
  template:
    src: "respondd.conf"
    dest: "{{ yanic_respondd_config }}"
  notify: restart respondd

- name: create systemd unit
  template:
    src: "respondd.service"
    dest: "/etc/systemd/system/respondd.service"
  notify: reload systemd

- name: configure systemd unit
  systemd:
    name: "respondd.service"
    enabled: yes
    state: started
